// Infographic generator — structured SVG approach.
//
// Why SVG? AI image models (DALL-E, Gemini, Imagen) all garble text inside
// infographics: chart labels become nonsense, numbers get mangled, headings
// turn into pseudo-letters. The only way to guarantee legible text is to
// render it with actual fonts — which means generating the *content*
// (via LLM) and the *visual* (via SVG with real text elements) separately.
//
// Pipeline:
//   1. LLM (Perplexity sonar) generates structured JSON describing the
//      infographic's content: title, subtitle, sections (heading, stat,
//      stat_label, body, icon_hint), and footer.
//   2. This edge function builds an SVG from that JSON using a fixed
//      professional layout. Text elements are crisp because they're
//      vector-rendered by the browser, not pixel-generated by an AI.
//   3. SVG is uploaded to the `article-covers` bucket as an .svg file.
//      <img src="*.svg"> works everywhere (browsers, email clients, RSS).
//
// Credits: 5 (same as the old DALL-E/Gemini approach).

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

// Color palettes for visual variety. The LLM picks a style; we map it
// to a palette. All are designed for white/light backgrounds with
// WCAG-contrast-safe text colors.
const PALETTES: Record<string, { primary: string; secondary: string; accent: string; bg: string; cardBg: string; text: string; muted: string }> = {
  comparison: { primary: "#2563EB", secondary: "#7C3AED", accent: "#F59E0B", bg: "#F8FAFC", cardBg: "#FFFFFF", text: "#0F172A", muted: "#64748B" },
  stats:      { primary: "#059669", secondary: "#0284C7", accent: "#DC2626", bg: "#F0FDF4", cardBg: "#FFFFFF", text: "#0F172A", muted: "#64748B" },
  timeline:   { primary: "#7C3AED", secondary: "#2563EB", accent: "#F97316", bg: "#FAF5FF", cardBg: "#FFFFFF", text: "#0F172A", muted: "#64748B" },
  process:    { primary: "#0891B2", secondary: "#4F46E5", accent: "#16A34A", bg: "#F0F9FF", cardBg: "#FFFFFF", text: "#0F172A", muted: "#64748B" },
  general:    { primary: "#3B82F6", secondary: "#8B5CF6", accent: "#EF4444", bg: "#F8FAFC", cardBg: "#FFFFFF", text: "#0F172A", muted: "#64748B" },
};

// Shape of the JSON the LLM returns. Kept simple so it doesn't hallucinate.
interface InfographicData {
  title: string;
  subtitle?: string;
  sections: Array<{
    heading: string;
    stat?: string;
    stat_label?: string;
    body: string;
  }>;
  footer?: string;
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    // Auth
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return json({ error: "Unauthorized" }, 401);
    }
    const supabaseAuth = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } },
    );
    const { data: { user }, error: authError } = await supabaseAuth.auth.getUser();
    if (authError || !user) return json({ error: "Unauthorized" }, 401);

    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );
    const { data: hasCredits } = await supabaseAdmin.rpc("deduct_credits", {
      p_user_id: user.id,
      p_amount: 5,
      p_action: "generate_infographic",
    });
    if (!hasCredits) {
      return json({ error: "Insufficient credits", code: "NO_CREDITS" }, 402);
    }

    const { prompt, style = "general" } = await req.json();
    if (!prompt) return json({ error: "Prompt is required" }, 400);

    // Stage 1 — LLM generates structured content.
    const infographicData = await generateContent(prompt, style);

    // Stage 2 — Build SVG from the structured content.
    const palette = PALETTES[style] || PALETTES.general;
    const svg = buildSvg(infographicData, palette);

    // Stage 3 — Upload SVG to storage.
    const fileName = `infographic-${Date.now()}-${Math.random().toString(36).substring(7)}.svg`;
    const filePath = `infographics/${fileName}`;
    const svgBytes = new TextEncoder().encode(svg);

    const { error: uploadError } = await supabaseAdmin.storage
      .from("article-covers")
      .upload(filePath, svgBytes, {
        contentType: "image/svg+xml",
        upsert: false,
      });

    if (uploadError) {
      console.error("Storage upload error:", uploadError);
      throw new Error(`Failed to upload infographic: ${uploadError.message}`);
    }

    const { data: urlData } = supabaseAdmin.storage
      .from("article-covers")
      .getPublicUrl(filePath);

    return json({ image_url: urlData.publicUrl });
  } catch (e) {
    console.error("generate-infographic error:", e);
    return json({ error: e instanceof Error ? e.message : "Unknown error" }, 500);
  }
});

// ---------------------------------------------------------------------------
// Stage 1: LLM content generation
// ---------------------------------------------------------------------------

async function generateContent(prompt: string, style: string): Promise<InfographicData> {
  const PERPLEXITY_API_KEY = Deno.env.get("PERPLEXITY_API_KEY");
  const OPENAI_API_KEY = Deno.env.get("OPENAI_API_KEY");

  const systemPrompt = `You generate structured infographic content as JSON. Given a topic, produce a JSON object with this exact shape:

{
  "title": "Short punchy title (max 8 words)",
  "subtitle": "One sentence explaining what this infographic shows",
  "sections": [
    {
      "heading": "Section name (3-5 words)",
      "stat": "72%",
      "stat_label": "of companies report improvement",
      "body": "One concise sentence with a key detail or insight."
    }
  ],
  "footer": "Source: [attribution if available]"
}

Rules:
- Output ONLY valid JSON. No markdown, no code fences, no explanation.
- sections: exactly 4-6 items. No more, no fewer.
- stat: a number with unit (%, $, x, k, M). Make it specific and factual from the topic. If no stat fits, omit the stat field for that section.
- stat_label: short phrase explaining the stat (under 8 words).
- heading: brief label for the section (3-5 words).
- body: one sentence, concrete and specific. No filler.
- title: catchy, max 8 words. Not a question.
- Style hint: ${style}. Adapt the section structure (comparison → use vs. language; timeline → chronological; process → sequential steps; stats → lead with numbers).
- Do NOT invent statistics. If a number isn't established, use a directional claim ("3x faster" is OK if supported, "87.3% improvement" without a source is not).`;

  const userMessage = `Create infographic content about: ${prompt}`;

  let responseText: string | null = null;

  // Try Perplexity first (grounded in web data), fall back to OpenAI.
  if (PERPLEXITY_API_KEY) {
    try {
      const res = await fetch("https://api.perplexity.ai/chat/completions", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${PERPLEXITY_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "sonar",
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userMessage },
          ],
          stream: false,
        }),
      });
      if (res.ok) {
        const data = await res.json();
        responseText = data.choices?.[0]?.message?.content ?? null;
      }
    } catch (e) {
      console.warn("Perplexity failed for infographic content:", e);
    }
  }

  if (!responseText && OPENAI_API_KEY) {
    try {
      const res = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${OPENAI_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "gpt-4o-mini",
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userMessage },
          ],
          response_format: { type: "json_object" },
          temperature: 0.7,
        }),
      });
      if (res.ok) {
        const data = await res.json();
        responseText = data.choices?.[0]?.message?.content ?? null;
      }
    } catch (e) {
      console.warn("OpenAI failed for infographic content:", e);
    }
  }

  if (!responseText) {
    throw new Error("No LLM provider available for infographic content generation");
  }

  // Parse JSON — strip any markdown fences the model might wrap it in.
  const cleaned = responseText
    .replace(/^```json\s*/i, "")
    .replace(/^```\s*/i, "")
    .replace(/\s*```$/i, "")
    .trim();

  try {
    const parsed = JSON.parse(cleaned) as InfographicData;
    if (!parsed.title || !Array.isArray(parsed.sections) || parsed.sections.length === 0) {
      throw new Error("Missing required fields");
    }
    // Clamp to 6 sections max.
    parsed.sections = parsed.sections.slice(0, 6);
    return parsed;
  } catch (e) {
    console.error("Infographic JSON parse failed:", cleaned.slice(0, 500));
    throw new Error(`Failed to parse infographic content: ${e instanceof Error ? e.message : e}`);
  }
}

// ---------------------------------------------------------------------------
// Stage 2: SVG rendering
// ---------------------------------------------------------------------------

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

// Word-wrap a string into lines of approximately `maxChars` each.
function wrapText(text: string, maxChars: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    if (line.length + word.length + 1 > maxChars && line.length > 0) {
      lines.push(line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) lines.push(line);
  return lines;
}

function buildSvg(
  data: InfographicData,
  p: { primary: string; secondary: string; accent: string; bg: string; cardBg: string; text: string; muted: string },
): string {
  const W = 800;
  const CARD_W = 340;
  const CARD_H = 180;
  const CARD_GAP = 24;
  const COLS = 2;
  const MARGIN_X = (W - COLS * CARD_W - (COLS - 1) * CARD_GAP) / 2;

  const sectionCount = data.sections.length;
  const rows = Math.ceil(sectionCount / COLS);

  // Header height: title + subtitle + padding.
  const HEADER_Y = 48;
  const TITLE_H = 48;
  const SUBTITLE_H = data.subtitle ? 28 : 0;
  const HEADER_TOTAL = HEADER_Y + TITLE_H + SUBTITLE_H + 32;

  // Footer.
  const FOOTER_H = data.footer ? 56 : 24;

  const GRID_TOP = HEADER_TOTAL;
  const GRID_H = rows * CARD_H + (rows - 1) * CARD_GAP;
  const H = GRID_TOP + GRID_H + FOOTER_H;

  // Decorative accent bar colors per card (cycle through primary/secondary/accent).
  const accentColors = [p.primary, p.secondary, p.accent, p.primary, p.secondary, p.accent];

  let cards = "";
  data.sections.forEach((sec, i) => {
    const col = i % COLS;
    const row = Math.floor(i / COLS);
    const x = MARGIN_X + col * (CARD_W + CARD_GAP);
    const y = GRID_TOP + row * (CARD_H + CARD_GAP);
    const barColor = accentColors[i % accentColors.length];

    // Card background with rounded rect + left accent bar.
    cards += `<rect x="${x}" y="${y}" width="${CARD_W}" height="${CARD_H}" rx="12" fill="${p.cardBg}" filter="url(#shadow)"/>`;
    cards += `<rect x="${x}" y="${y}" width="5" height="${CARD_H}" rx="3" fill="${barColor}"/>`;

    // Heading.
    cards += `<text x="${x + 20}" y="${y + 28}" font-size="15" font-weight="700" fill="${p.text}" font-family="system-ui, -apple-system, 'Segoe UI', sans-serif">${esc(sec.heading)}</text>`;

    // Stat + label (if present).
    let bodyY = y + 52;
    if (sec.stat) {
      cards += `<text x="${x + 20}" y="${y + 58}" font-size="32" font-weight="800" fill="${barColor}" font-family="system-ui, -apple-system, 'Segoe UI', sans-serif">${esc(sec.stat)}</text>`;
      if (sec.stat_label) {
        cards += `<text x="${x + 20}" y="${y + 80}" font-size="12" fill="${p.muted}" font-family="system-ui, -apple-system, 'Segoe UI', sans-serif">${esc(sec.stat_label)}</text>`;
      }
      bodyY = y + 102;
    }

    // Body text (word-wrapped).
    const bodyLines = wrapText(sec.body, 42);
    bodyLines.forEach((line, li) => {
      if (bodyY + li * 18 < y + CARD_H - 12) {
        cards += `<text x="${x + 20}" y="${bodyY + li * 18}" font-size="12.5" fill="${p.muted}" font-family="system-ui, -apple-system, 'Segoe UI', sans-serif">${esc(line)}</text>`;
      }
    });
  });

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}">
  <defs>
    <filter id="shadow" x="-4%" y="-4%" width="108%" height="108%">
      <feDropShadow dx="0" dy="2" stdDeviation="6" flood-color="#000" flood-opacity="0.06"/>
    </filter>
  </defs>

  <!-- Background -->
  <rect width="${W}" height="${H}" fill="${p.bg}" rx="0"/>

  <!-- Top accent bar -->
  <rect width="${W}" height="6" fill="${p.primary}" rx="0"/>

  <!-- Title -->
  <text x="${W / 2}" y="${HEADER_Y + 36}" text-anchor="middle" font-size="28" font-weight="800" fill="${p.text}" font-family="system-ui, -apple-system, 'Segoe UI', sans-serif">${esc(data.title)}</text>

  ${data.subtitle ? `<!-- Subtitle -->
  <text x="${W / 2}" y="${HEADER_Y + TITLE_H + 20}" text-anchor="middle" font-size="14" fill="${p.muted}" font-family="system-ui, -apple-system, 'Segoe UI', sans-serif">${esc(data.subtitle)}</text>` : ""}

  <!-- Cards -->
  ${cards}

  ${data.footer ? `<!-- Footer -->
  <text x="${W / 2}" y="${H - 18}" text-anchor="middle" font-size="11" fill="${p.muted}" font-family="system-ui, -apple-system, 'Segoe UI', sans-serif">${esc(data.footer)}</text>` : ""}
</svg>`;
}

function json(payload: unknown, status = 200): Response {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}
