// Content Lab terms of service. Rendered at /terms. Public — no auth.
//
// These are plain-language terms, not a substitute for a full legal review.
// If you're going to rely on these commercially, run them past a lawyer
// who knows your jurisdiction.

export default function Terms() {
  return (
    <div className="container max-w-3xl py-12 text-foreground">
      <h1 className="mb-2 text-3xl font-bold tracking-tight">Terms of Service</h1>
      <p className="mb-8 text-sm text-muted-foreground">Last updated: April 15, 2026</p>

      <Section title="1. Accepting these terms">
        <p>
          By creating a Content Lab account, using the Content Lab web app, or connecting
          Content Lab to another service (including Claude via the MCP connector), you
          agree to these terms. If you don't agree, don't use the service.
        </p>
      </Section>

      <Section title="2. What Content Lab is">
        <p>
          Content Lab is a hosted SaaS that helps you draft, schedule, and publish written
          content (articles, social posts, newsletters). It uses third-party AI providers
          (currently Perplexity for text generation and optionally OpenAI DALL-E for cover
          images) to produce content based on your prompts.
        </p>
      </Section>

      <Section title="3. Your account">
        <ul>
          <li>You're responsible for keeping your login credentials secure.</li>
          <li>You're responsible for any action taken through your account, including actions performed by connected services (Claude, automations, etc.).</li>
          <li>One account per person or company. Don't share logins.</li>
        </ul>
      </Section>

      <Section title="4. Acceptable use">
        <p>You may not use Content Lab to:</p>
        <ul>
          <li>Generate content that's illegal, deceptive, or intended to harm others.</li>
          <li>Impersonate anyone or misrepresent who published the content.</li>
          <li>Reverse-engineer, scrape, or try to extract prompts from the service.</li>
          <li>Interfere with the service's operation or other users' access to it.</li>
          <li>Violate the terms of any connected third-party service (LinkedIn, Resend, Framer, Intercom, Notion).</li>
        </ul>
        <p>We may suspend or terminate accounts that violate these rules.</p>
      </Section>

      <Section title="5. Credits and billing">
        <p>
          Content Lab is sold on a credit-based model. Each generation (article, social
          post, cover image) deducts credits from your balance. Credits are non-refundable
          once used. If a generation fails due to our error, we refund the credits; if it
          fails due to your input, we don't.
        </p>
        <p>
          Subscription billing is handled by Stripe. You can cancel at any time; billing
          stops at the end of the current period. No prorated refunds.
        </p>
      </Section>

      <Section title="6. Content you create">
        <p>
          You own the content you generate with Content Lab. We don't claim any rights to
          it and we don't use it to train AI models.
        </p>
        <p>
          You're responsible for how you use the output. AI-generated content can be
          inaccurate — verify facts, statistics, and quotes before publishing. Cover
          images generated by DALL-E may reflect training-data biases.
        </p>
      </Section>

      <Section title="7. Service availability">
        <p>
          We aim for reliable uptime but don't guarantee the service will be available
          without interruption. Scheduled maintenance, provider outages (Supabase,
          Perplexity, OpenAI, Resend, LinkedIn), and unforeseen incidents can interrupt
          access. We're not liable for missed publishes caused by these outages.
        </p>
      </Section>

      <Section title="8. Third-party integrations">
        <p>
          When you connect a third-party service (LinkedIn, Resend, Framer, Intercom,
          Notion, Claude via MCP), you grant Content Lab permission to perform the
          actions defined by the scopes you approve. Content Lab is not responsible for
          changes to third-party APIs, terms, or pricing.
        </p>
      </Section>

      <Section title="9. Warranty and liability">
        <p>
          Content Lab is provided "as is". To the maximum extent permitted by law, we
          disclaim implied warranties of merchantability, fitness for a particular
          purpose, and non-infringement. Our aggregate liability for any claim arising
          from your use of Content Lab is capped at the amount you paid us in the 12
          months preceding the claim.
        </p>
      </Section>

      <Section title="10. Termination">
        <p>
          You can cancel your account any time from Settings. We can terminate accounts
          that violate these terms. On termination, your content and integration tokens
          are removed within 30 days.
        </p>
      </Section>

      <Section title="11. Changes">
        <p>
          We may update these terms when the product changes materially. We'll update the
          "last updated" date above; significant changes will be announced by email.
          Continued use after the change means you accept the new terms.
        </p>
      </Section>

      <Section title="12. Contact">
        <p>
          Questions? <a className="underline" href="mailto:support@content-lab.ie">support@content-lab.ie</a>.
        </p>
      </Section>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8 [&_p]:mb-3 [&_p]:text-sm [&_p]:text-muted-foreground [&_p]:leading-relaxed [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:mb-3 [&_ul]:space-y-1 [&_ul>li]:text-sm [&_ul>li]:text-muted-foreground [&_ul>li]:leading-relaxed [&_a]:text-primary [&_strong]:text-foreground">
      <h2 className="mb-3 text-lg font-semibold text-foreground">{title}</h2>
      {children}
    </section>
  );
}
