-- Applied on prod via direct SQL (dashboard or MCP) before this project
-- adopted the migration CLI. The DDL originally here is already in place
-- in the live database — re-running it would fail on duplicate-object
-- errors. Kept as an empty stub so `supabase migration list` matches
-- what's actually tracked in the remote `schema_migrations` table.
--
-- The original SQL is preserved in git history: `git log --follow supabase/migrations/20260319045814_create_user_integrations.sql`
